doctrine:
    orm:
        mappings:
            ControleOnline:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/modules/controleonline/ead/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
